# Generated by Django 3.1.5 on 2021-04-16 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0002_aaghazerrors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_eduction', models.CharField(blank=True, max_length=100, null=True)),
                ('educational_institution', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedIn_profile', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_profile', models.CharField(blank=True, max_length=100, null=True)),
                ('aadhar_card', models.PositiveIntegerField(blank=True, null=True, verbose_name='Adhaar Card')),
                ('current_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('office_address', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vol_model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
